version: "3.8"

name: annos-dev

services:
    annos-server:
        container_name: annos_server
        build:
            context: ../server
            dockerfile: ./Dockerfile
            target: dev
        environment:
            - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1
        ports:
            - 8080:8080
        command: dotnet watch run --no-restore --non-interactive
        restart: no
        volumes:
            - ../server/:/build
            - /build/obj
            - /build/bin
    
    annos-web:
        container_name: annos_web
        build:
            context: ../web
            dockerfile: ./Dockerfile
        ports:
            - 4200:4200
        restart: no
        volumes:
            - ../web/src:/usr/src/app/src

    annos-db:
        container_name: annos_db
        image: postgres:16-alpine
        ports:
            - 5432:5432
        restart: no
        volumes:
            - ../db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=dev
